### PR TITLE
fix: Don't run out of memory when evaluating infinite recursive programs

### PR DESCRIPTION
**Pull request by Marwes**

### CODE REVIEW

**Comment by brendanzab** [comment]
I need commit access to merge though! 😉

**Comment by Marwes** [comment]
Sent you a collaborator invite to this repo and the language-server a day or so ago (forgot to say anything) did they get lost somehow?

**Comment by brendanzab** [comment]
Weird - I thought I accepted it :/

**Comment by Marwes** [comment]
Says it's pending for me, should I resend them?

**Pull request merged**
